name: Test grammar

on:
  push:
    branches:
      - master
      - main
    paths:
      - grammar.js
      - src/**
      - bindings/**
      - binding.gyp
  pull_request:
    paths:
      - grammar.js
      - src/**
      - bindings/**
      - binding.gyp

jobs:
  test:
    uses: tree-sitter-grammars/.github/.github/workflows/ci.yml@main
    if: "!github.event.repository.is_template && github.event.head_commit.message != 'Initial commit'"
    with:
      # NOTE: change to true to also test the rust library:
      test-library: false
  # NOTE: uncomment this job if you use an external scanner:
  # fuzz:
  #   name: Fuzz parser
  #   runs-on: ubuntu-latest
  #   steps:
  #    - uses: actions/checkout@v4
  #    - uses: tree-sitter-grammars/tree-sitter-fuzz-action@v3
