name: CI

on:
  push:
    branches:
      - master
      - main
    paths:
      - grammar.js
      - src/**
      - bindings/**
      - binding.gyp
  pull_request:
    paths:
      - grammar.js
      - src/**
      - bindings/**
      - binding.gyp

jobs:
  test:
    name: Test parser
    runs-on: ${{matrix.os}}
    if: "!github.event.repository.is_template && github.event.head_commit.message != 'Initial commit'"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: ${{vars.NODE_VERSION}}
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.8
        if: runner.os == 'macOS'
      - name: Install dependencies
        shell: sh
        run: npm ci
      - name: Run tests
        uses: tree-sitter-grammars/actions/test@main
        with:
          test-library: ${{runner.os == 'Linux'}}
      - name: Check for scanner changes
        id: scanner-check
        shell: sh
        run: |-
          {
            test -f src/scanner.c && ! git diff --quiet -- "$_" &&
            printf 'changed=true\n' || printf 'changed=false\n'
          } >> "$GITHUB_OUTPUT"
      - name: Fuzz scanner
        uses: tree-sitter-grammars/tree-sitter-fuzz-action@v3
        if: steps.scanner-check.outputs.changed == 'true'
